// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: raft.proto

package kvgo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RafterClient is the client API for Rafter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RafterClient interface {
	AppendEntry(ctx context.Context, in *AppendEntryRequest, opts ...grpc.CallOption) (*AppendEntryResponse, error)
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type rafterClient struct {
	cc grpc.ClientConnInterface
}

func NewRafterClient(cc grpc.ClientConnInterface) RafterClient {
	return &rafterClient{cc}
}

func (c *rafterClient) AppendEntry(ctx context.Context, in *AppendEntryRequest, opts ...grpc.CallOption) (*AppendEntryResponse, error) {
	out := new(AppendEntryResponse)
	err := c.cc.Invoke(ctx, "/kvgo.Rafter/AppendEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rafterClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, "/kvgo.Rafter/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RafterServer is the server API for Rafter service.
// All implementations must embed UnimplementedRafterServer
// for forward compatibility
type RafterServer interface {
	AppendEntry(context.Context, *AppendEntryRequest) (*AppendEntryResponse, error)
	Vote(context.Context, *VoteRequest) (*VoteResponse, error)
	mustEmbedUnimplementedRafterServer()
}

// UnimplementedRafterServer must be embedded to have forward compatible implementations.
type UnimplementedRafterServer struct {
}

func (UnimplementedRafterServer) AppendEntry(context.Context, *AppendEntryRequest) (*AppendEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntry not implemented")
}
func (UnimplementedRafterServer) Vote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedRafterServer) mustEmbedUnimplementedRafterServer() {}

// UnsafeRafterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RafterServer will
// result in compilation errors.
type UnsafeRafterServer interface {
	mustEmbedUnimplementedRafterServer()
}

func RegisterRafterServer(s grpc.ServiceRegistrar, srv RafterServer) {
	s.RegisterService(&Rafter_ServiceDesc, srv)
}

func _Rafter_AppendEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RafterServer).AppendEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvgo.Rafter/AppendEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RafterServer).AppendEntry(ctx, req.(*AppendEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rafter_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RafterServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvgo.Rafter/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RafterServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rafter_ServiceDesc is the grpc.ServiceDesc for Rafter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rafter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvgo.Rafter",
	HandlerType: (*RafterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntry",
			Handler:    _Rafter_AppendEntry_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Rafter_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
